# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy all files to work directory
COPY . .

# Install dependencies and build the project
RUN npm ci && npm run build

# Expose the port the server listens on (if applicable)
EXPOSE 3000

# Set the default command
CMD ["node", "dist/index.js"]
